version: '3.6'

services:
  postgresql:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: bram
      POSTGRES_PASSWORD:
      POSTGRES_DB: homepage
