version: '3.5'

services:
  db:
    image: postgres:10.2-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: bram
      POSTGRES_PASSWORD:
      POSTGRES_DB: homepage
