version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: bram
          POSTGRES_PASSWORD:
          POSTGRES_DB: homepage

    working_directory: ~/homepage

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: gradle test
